#loki-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: loki-server
data:
  loki.yaml: |
    # Authentication 설정을 비활성화합니다.
    auth_enabled: false

    # 리소스 사용 및 동작을 제한하기 위한 설정입니다.
    limits_config:
      allow_structured_metadata: false  # 구조화된 메타데이터 사용을 허용하지 않습니다.
      volume_enabled: true              # 로그 데이터 볼륨을 활성화합니다.
      reject_old_samples: true          # 오래된 샘플을 거부합니다.
      ingestion_rate_mb: 8              # 초당 최대 수집 속도를 8MB로 설정합니다.
      ingestion_burst_size_mb: 12       # 수집 버스트 크기를 12MB로 설정합니다.
      ingestion_rate_strategy: global
      reject_old_samples_max_age: 168h  # 오래된 샘플의 최대 나이를 168시간(7일)로 설정합니다.

    # 서버 관련 설정입니다.
    server:
      http_listen_port: 3100            # HTTP 요청을 수신할 포트 번호입니다.
      grpc_listen_port: 9095            # gRPC 요청을 수신할 포트 번호입니다.

    # 공통 설정으로, 클러스터링 및 저장소 관련 설정을 포함합니다.
    common:
      path_prefix: /data/loki        # 데이터 저장 경로의 접두사를 설정합니다.
      replication_factor: 1             # 복제 인수를 설정합니다.
      ring:
        instance_addr: "0.0.0.0"
        kvstore:
          store: memberlist             # KV 스토어를 memberlist로 설정합니다.
      storage:
        s3:
          endpoint: s3.ap-northeast-2.amazonaws.com   # S3 엔드포인트를 설정합니다.
          region: "ap-northeast-2"                    # AWS 지역을 설정합니다.
          bucketnames: temp-test-loki-20241120        # 사용할 S3 버킷 이름을 설정합니다.
          access_key_id: ${AWS_ACCESS_KEY_ID}         # AWS 액세스 키 ID를 설정합니다.
          secret_access_key: ${AWS_SECRET_ACCESS_KEY} # AWS 시크릿 액세스 키를 설정합니다.
          s3forcepathstyle: true                      # Path 스타일 S3 URL을 사용합니다.
          insecure: false                             # TLS 사용 여부를 설정합니다

    memberlist:
      bind_port: 7946  # memberlist가 사용하는 포트 번호입니다.

    # 스키마 설정으로, 로그 데이터의 저장 방식과 인덱스 구성을 정의합니다.
    schema_config:
      configs:
        - from: 2023-01-01
          store: tsdb                      # 스토리지 엔진을 tsdb로 설정합니다.
          object_store: s3                 # 객체 저장소 유형을 S3로 설정합니다.
          schema: v13                      # 스키마 버전을 v13으로 설정합니다.
          index:
            prefix: index_                 # 인덱스 파일의 접두사를 설정합니다.
            period: 24h                    # 인덱스 데이터의 주기를 설정합니다.

    # 인제스터 설정으로, 로그 데이터를 수집하고 저장하는 방식을 정의합니다.
    ingester:
      lifecycler:
        address: "0.0.0.0"                 # 인스턴스 주소를 모든 인터페이스로 설정합니다.
        ring:
          kvstore:
            store: memberlist              # KV 스토어를 memberlist로 설정합니다.
          replication_factor: 1            # 복제 인수를 설정합니다.
        final_sleep: 0s                    # 인제스터가 종료될 때 대기할 시간을 설정합니다.
      wal:
        enabled: false                     # WAL(Write-Ahead Log)을 활성화합니다.

    # 컴팩터 설정으로, 오래된 로그 데이터를 정리하는 작업을 정의합니다.
    compactor:
      working_directory: /data/loki/compactor  # 컴팩터의 작업 디렉토리 경로를 설정합니다.
        #shared_store: s3                         # 공유 저장소를 S3로 설정합니다.

    # 룰러 설정으로, 알람 룰 등을 관리합니다 (필요한 경우 추가).
    ruler:
      storage:
        s3:
          endpoint: s3.ap-northeast-2.amazonaws.com
          region: "ap-northeast-2"
          bucketnames: temp-test-loki-20241120
          access_key_id: ${AWS_ACCESS_KEY_ID}
          secret_access_key: ${AWS_SECRET_ACCESS_KEY}
          s3forcepathstyle: true
          insecure: false
