#Service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: linket
spec:
  selector:
    app: frontend-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
