#alermanager-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: prometheus-server
  labels:
    app: alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    templates:
      - /etc/alertmanager/templates/*.tmpl

    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      receiver: 'discord'

    receivers:
      - name: 'discord'
        discord_configs:
          - webhook_url: "{{ discord_webhook_URL }}"
            send_resolved: true
            title: '{{ template "discord.default.title" . }}'
            message: '{{ template "discord.default.message" . }}'

    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname']
