---
# roles/nfs/tasks/install_nfs.yml

- name: Install NFS kernel server on masters
  package:
    name: nfs-kernel-server
    state: present
  when: "'masters' in group_names"

# 2. 마스터가 아닌 모든 노드에 nfs-common 설치
- name: Install NFS common on non-master nodes
  package:
    name: nfs-common
    state: present
  when: "'masters' not in group_names"

- name: Ensure /nfs_shared directory exists
  file:
    path: /nfs_shared
    state: directory
    mode: "0755"

- name: Create NFS shared subdirectories
  file:
    path: "/nfs_shared/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - jenkins_home
    - vault
    - prometheus
    - metrics
    - redis
    - grafana
    - elasticsearch

- name: Set ownership of /nfs_shared and its subdirectories
  file:
    path: /nfs_shared
    owner: "1000"
    group: "1000"
    recurse: yes

- name: Configure /etc/exports for NFS shares (Masters only)
  blockinfile:
    path: /etc/exports
    block: |
      /nfs_shared/jenkins_home 10.0.0.0/16(rw,sync,no_root_squash,no_subtree_check)
      /nfs_shared/vault 10.0.0.0/16(rw,sync,no_root_squash,no_subtree_check)
      /nfs_shared/prometheus 10.0.0.0/16(rw,sync,no_root_squash,no_subtree_check)
      /nfs_shared/metrics 10.0.0.0/16(rw,sync,no_root_squash,no_subtree_check)
      /nfs_shared/redis 10.0.0.0/16(rw,sync,no_root_squash,no_subtree_check)
      /nfs_shared/grafana 10.0.0.0/16(rw,sync,no_root_squash,no_subtree_check)
      /nfs_shared/elasticsearch 10.0.0.0/16(rw,sync,no_root_squash,no_subtree_check)
  when: "'masters' in group_names"

- name: Export NFS shares (Masters only)
  command: exportfs -r
  when: "'masters' in group_names"
