#filebeat-DaemonSet.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: kube-system
  labels:
    k8s-app: filebeat
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      k8s-app: filebeat
  template:
    metadata:
      labels:
        k8s-app: filebeat
    spec:
      serviceAccountName: filebeat
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          effect: NoSchedule
      containers:
        - name: filebeats
          image: docker.elastic.co/beats/filebeat:8.16.1
          args: ["-c", "/usr/share/filebeat/filebeat.yml", "-e"]
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: config
              mountPath: /usr/share/filebeat/filebeat.yml
              readOnly: true
              subPath: filebeat.yml
            - name: var-log-containers
              mountPath: /var/log/containers
              readOnly: true
            - name: var-log-pods
              mountPath: /var/log/pods
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: filebeat-config
            defaultMode: 0644
        - name: var-log-containers
          hostPath:
            path: /var/log/containers
        - name: var-log-pods
          hostPath:
            path: /var/log/pods
