#Kibana-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      nodeName: elk-worker
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.16.1
          env:
            - name: ELASTICSEARCH_USERNAME
              value: "kibana_system"
            - name: ELASTICSEARCH_PASSWORD
              value: "password"
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch-svc.elk.svc.cluster.local:9200"
          ports:
            - containerPort: 5601
