#logstash.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-yml
  namespace: elk
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch-svc.elk.svc.cluster.local:9200"]
    path.config: /usr/share/logstash/pipeline
