apiVersion: batch/v1
kind: Job
metadata:
  namespace: { { kaniko-namespace } }
  name: { { kaniko-job-name } } # Jenkinsfile에서 name 일치 시켜줘야 함
spec:
  template:
    metadata:
      name: { { kaniko-job-name } } # Jenkinsfile에서 name 일치 시켜줘야 함
    spec:
      nodeSelector:
        role: { { kaniko-namespace } }
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          env:
            - name: GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kaniko-secret
                  key: GIT_TOKEN
          args:
            [
              "--dockerfile=Dockerfile",
              "--context=git://github.com/animal-squad/project-s-BE.git#refs/heads/main",
              "--destination=ghcr.io/animal-squad/project-s-be:0b9aa46",
              "--build-arg=GIT_CREDENTIALS=${GIT_TOKEN}",
              "--cache=true",
              "--cache-repo=ghcr.io/animal-squad/project-s-be-kaniko-cache",
            ]
          volumeMounts:
            - name: ghcr-secret
              mountPath: /kaniko/.docker
      restartPolicy: Never

      volumes:
        - name: ghcr-secret
          secret:
            secretName: ghcr-secret # 생성한 docker-registry secret을 이름
            items:
              - key: .dockerconfigjson
                path: config.json
