---
# roles/install_k8s/vars/main.yml

arch_mapping_var:
  x86_64: amd64
  aarch64: arm64
  #ppc64le: ppc64el
  #s390x: s390x

packages:
  - tree
  - curl
  - gnupg2
  - software-properties-common
  - apt-transport-https
  - ca-certificates

k8s_version: v1.32